<?php

namespace Platform\Crm\Database\Seeders;

use Illuminate\Database\Seeder;
use Platform\Crm\Models\CrmCountry;

class CrmCountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Deutschland', 'code' => 'DE'],
            ['name' => 'Österreich', 'code' => 'AT'],
            ['name' => 'Schweiz', 'code' => 'CH'],
            ['name' => 'Liechtenstein', 'code' => 'LI'],
            ['name' => 'Luxemburg', 'code' => 'LU'],
            ['name' => 'Belgien', 'code' => 'BE'],
            ['name' => 'Niederlande', 'code' => 'NL'],
            ['name' => 'Dänemark', 'code' => 'DK'],
            ['name' => 'Schweden', 'code' => 'SE'],
            ['name' => 'Norwegen', 'code' => 'NO'],
            ['name' => 'Finnland', 'code' => 'FI'],
            ['name' => 'Island', 'code' => 'IS'],
            ['name' => 'Frankreich', 'code' => 'FR'],
            ['name' => 'Italien', 'code' => 'IT'],
            ['name' => 'Spanien', 'code' => 'ES'],
            ['name' => 'Portugal', 'code' => 'PT'],
            ['name' => 'Griechenland', 'code' => 'GR'],
            ['name' => 'Polen', 'code' => 'PL'],
            ['name' => 'Tschechien', 'code' => 'CZ'],
            ['name' => 'Slowakei', 'code' => 'SK'],
            ['name' => 'Ungarn', 'code' => 'HU'],
            ['name' => 'Rumänien', 'code' => 'RO'],
            ['name' => 'Bulgarien', 'code' => 'BG'],
            ['name' => 'Kroatien', 'code' => 'HR'],
            ['name' => 'Slowenien', 'code' => 'SI'],
            ['name' => 'Estland', 'code' => 'EE'],
            ['name' => 'Lettland', 'code' => 'LV'],
            ['name' => 'Litauen', 'code' => 'LT'],
            ['name' => 'Vereinigtes Königreich', 'code' => 'GB'],
            ['name' => 'Irland', 'code' => 'IE'],
            ['name' => 'Malta', 'code' => 'MT'],
            ['name' => 'Zypern', 'code' => 'CY'],
            ['name' => 'Vereinigte Staaten', 'code' => 'US'],
            ['name' => 'Kanada', 'code' => 'CA'],
            ['name' => 'Australien', 'code' => 'AU'],
            ['name' => 'Neuseeland', 'code' => 'NZ'],
            ['name' => 'Japan', 'code' => 'JP'],
            ['name' => 'Südkorea', 'code' => 'KR'],
            ['name' => 'China', 'code' => 'CN'],
            ['name' => 'Indien', 'code' => 'IN'],
            ['name' => 'Brasilien', 'code' => 'BR'],
            ['name' => 'Argentinien', 'code' => 'AR'],
            ['name' => 'Mexiko', 'code' => 'MX'],
            ['name' => 'Südafrika', 'code' => 'ZA'],
            ['name' => 'Russland', 'code' => 'RU'],
            ['name' => 'Ukraine', 'code' => 'UA'],
            ['name' => 'Türkei', 'code' => 'TR'],
            ['name' => 'Israel', 'code' => 'IL'],
            ['name' => 'Vereinigte Arabische Emirate', 'code' => 'AE'],
            ['name' => 'Saudi-Arabien', 'code' => 'SA'],
            ['name' => 'Ägypten', 'code' => 'EG'],
            ['name' => 'Marokko', 'code' => 'MA'],
            ['name' => 'Tunesien', 'code' => 'TN'],
            ['name' => 'Algerien', 'code' => 'DZ'],
            ['name' => 'Libyen', 'code' => 'LY'],
            ['name' => 'Nigeria', 'code' => 'NG'],
            ['name' => 'Kenia', 'code' => 'KE'],
            ['name' => 'Ghana', 'code' => 'GH'],
            ['name' => 'Senegal', 'code' => 'SN'],
            ['name' => 'Elfenbeinküste', 'code' => 'CI'],
            ['name' => 'Kamerun', 'code' => 'CM'],
            ['name' => 'Gabun', 'code' => 'GA'],
            ['name' => 'Kongo', 'code' => 'CG'],
            ['name' => 'Demokratische Republik Kongo', 'code' => 'CD'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Namibia', 'code' => 'NA'],
            ['name' => 'Botswana', 'code' => 'BW'],
            ['name' => 'Simbabwe', 'code' => 'ZW'],
            ['name' => 'Sambia', 'code' => 'ZM'],
            ['name' => 'Malawi', 'code' => 'MW'],
            ['name' => 'Mosambik', 'code' => 'MZ'],
            ['name' => 'Madagaskar', 'code' => 'MG'],
            ['name' => 'Mauritius', 'code' => 'MU'],
            ['name' => 'Seychellen', 'code' => 'SC'],
            ['name' => 'Komoren', 'code' => 'KM'],
            ['name' => 'Dschibuti', 'code' => 'DJ'],
            ['name' => 'Äthiopien', 'code' => 'ET'],
            ['name' => 'Eritrea', 'code' => 'ER'],
            ['name' => 'Somalia', 'code' => 'SO'],
            ['name' => 'Sudan', 'code' => 'SD'],
            ['name' => 'Südsudan', 'code' => 'SS'],
            ['name' => 'Tschad', 'code' => 'TD'],
            ['name' => 'Niger', 'code' => 'NE'],
            ['name' => 'Mali', 'code' => 'ML'],
            ['name' => 'Burkina Faso', 'code' => 'BF'],
            ['name' => 'Benin', 'code' => 'BJ'],
            ['name' => 'Togo', 'code' => 'TG'],
            ['name' => 'Liberia', 'code' => 'LR'],
            ['name' => 'Sierra Leone', 'code' => 'SL'],
            ['name' => 'Guinea', 'code' => 'GN'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW'],
            ['name' => 'Kap Verde', 'code' => 'CV'],
            ['name' => 'Gambia', 'code' => 'GM'],
            ['name' => 'Mauretanien', 'code' => 'MR'],
            ['name' => 'West-Sahara', 'code' => 'EH'],
            ['name' => 'Äquatorialguinea', 'code' => 'GQ'],
            ['name' => 'São Tomé und Príncipe', 'code' => 'ST'],
            ['name' => 'Zentralafrikanische Republik', 'code' => 'CF'],
            ['name' => 'Tschad', 'code' => 'TD'],
            ['name' => 'Kamerun', 'code' => 'CM'],
            ['name' => 'Gabun', 'code' => 'GA'],
            ['name' => 'Kongo', 'code' => 'CG'],
            ['name' => 'Demokratische Republik Kongo', 'code' => 'CD'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Namibia', 'code' => 'NA'],
            ['name' => 'Botswana', 'code' => 'BW'],
            ['name' => 'Simbabwe', 'code' => 'ZW'],
            ['name' => 'Sambia', 'code' => 'ZM'],
            ['name' => 'Malawi', 'code' => 'MW'],
            ['name' => 'Mosambik', 'code' => 'MZ'],
            ['name' => 'Madagaskar', 'code' => 'MG'],
            ['name' => 'Mauritius', 'code' => 'MU'],
            ['name' => 'Seychellen', 'code' => 'SC'],
            ['name' => 'Komoren', 'code' => 'KM'],
            ['name' => 'Dschibuti', 'code' => 'DJ'],
            ['name' => 'Äthiopien', 'code' => 'ET'],
            ['name' => 'Eritrea', 'code' => 'ER'],
            ['name' => 'Somalia', 'code' => 'SO'],
            ['name' => 'Sudan', 'code' => 'SD'],
            ['name' => 'Südsudan', 'code' => 'SS'],
            ['name' => 'Tschad', 'code' => 'TD'],
            ['name' => 'Niger', 'code' => 'NE'],
            ['name' => 'Mali', 'code' => 'ML'],
            ['name' => 'Burkina Faso', 'code' => 'BF'],
            ['name' => 'Benin', 'code' => 'BJ'],
            ['name' => 'Togo', 'code' => 'TG'],
            ['name' => 'Liberia', 'code' => 'LR'],
            ['name' => 'Sierra Leone', 'code' => 'SL'],
            ['name' => 'Guinea', 'code' => 'GN'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW'],
            ['name' => 'Kap Verde', 'code' => 'CV'],
            ['name' => 'Gambia', 'code' => 'GM'],
            ['name' => 'Mauretanien', 'code' => 'MR'],
            ['name' => 'West-Sahara', 'code' => 'EH'],
            ['name' => 'Äquatorialguinea', 'code' => 'GQ'],
            ['name' => 'São Tomé und Príncipe', 'code' => 'ST'],
            ['name' => 'Zentralafrikanische Republik', 'code' => 'CF'],
        ];
        
        foreach ($countries as $country) {
            CrmCountry::firstOrCreate(
                ['code' => $country['code']],
                [
                    'name' => $country['name'],
                    'code' => $country['code'],
                    'is_active' => true,
                ]
            );
        }
    }
} 